[workspace]
members = [
    "rsa", "rsa-fdh-vrf", "ecvrf", "ed25519-hash", "pearlitefun", "nohacspec"]
default-members = [
    "rsa", "rsa-fdh-vrf", "ecvrf", "ed25519-hash", "pearlitefun", "nohacspec"]
